name: Release
on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f ../.github/goreleaser.yml
          workdir: mkvtool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NAME: "mkvtool"

      - name: Dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/